### ISSUE TITLE
Error while adding doctor to the network

### ISSUE THREAD

**Issue by FOG-ntp** [subhamkumarr/FlipKart_Grid_5.0#1]
Hello there,

I have setup the whole project . Things are working as expected. I am facing an error while adding a doctor to the network.
![image](https://github.com/subhamkumarr/FlipKart_Grid_5.0/assets/99815527/6609db57-f1e9-40c8-9f02-6e7e0d28694f)

Thank you in advance.

**Comment by subhamkumarr** [comment]
Check your ganache setup.
